version: '3'

services:
  tc-srv:
    image: jetbrains/teamcity-server
    container_name: tc-srv
    volumes:
      - /home/andrew/tmp/TeamCity/srv/data:/data/teamcity_server/datadir
      - /home/andrew/tmp/TeamCity/srv/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    networks:
      - tc-net
  tc-ag1:
    image: jetbrains/teamcity-agent
    container_name: tc-ag1
    environment:
      SERVER_URL: http://tc-srv:8111
    volumes:
      - /home/andrew/tmp/TeamCity/agent1/conf:/data/teamcity_agent/conf
    networks:
      - tc-net
networks:
  tc-net:
    driver: bridge
