version: "3"

services:
 mysql:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: "dat1a57"
   MYSQL_DATABASE: "wimb"
  ports:
   - 6603:3306
  volumes:
   - /home/ubuntu/mysql/data:/var/lib/mysql
   - /home/ubuntu/mysql/conf:/etc/mysql/conf.d
   - /home/ubuntu/mysql/init:/docker-entrypoint-initdb.d
  deploy:
   placement:
    constraints:
     - node.labels.cluster-role == DB
  networks:
   - wimbnet
 wimb-dataservice:
  image: akozhanov/wimb-dataservice:latest
  ports:
   - 10000:10000
  links:
   - mysql:mysql
  deploy:
   replicas: 3
  networks:
   - wimbnet
networks:
 wimbnet:
