FROM node:6

WORKDIR /usr/src/app
RUN mkdir static

COPY ./clientservice/src/nodejs/package.json .
RUN npm install

COPY ./wait-for-it.sh /clientservice/clientservice-start.sh ./
RUN /bin/bash -c 'chmod +x ./wait-for-it.sh' && /bin/bash -c 'chmod +x ./clientservice-start.sh'

COPY ./clientservice/src/nodejs/*.* ./
COPY ./clientservice/src/nodejs/static/*.* ./static/

ENTRYPOINT ["./clientservice-start.sh"]
